CREATE TABLE cliente (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20),
    DATA_CADASTRO DATE DEFAULT CURDATE()
);

CREATE TABLE produto (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE INT NOT NULL
);

CREATE TABLE pedido (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_PEDIDO DATE DEFAULT CURDATE(),
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES cliente(ID_CLIENTE)
);