CREATE TABLE categoria (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO ENUM('Receita', 'Despesa') NOT NULL
);

CREATE TABLE lancamento (
    ID_LANCAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT,
    DESCRICAO VARCHAR(150),
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria(ID_CATEGORIA)
);