CREATE TABLE usuario (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_CADASTRO DATE DEFAULT CURDATE()
);

CREATE TABLE livro (
    ID_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    AUTOR VARCHAR(100),
    CATEGORIA VARCHAR(50),
    DISPONIVEL BOOLEAN DEFAULT 1
);

CREATE TABLE emprestimo (
    ID_EMPRESTIMO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ID_LIVRO INT,
    DATA_EMPRESTIMO DATE DEFAULT CURDATE(),
    DATA_DEVOLUCAO DATE,
    FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
    FOREIGN KEY (ID_LIVRO) REFERENCES livro(ID_LIVRO)
);